.PHONY: install cims demo seed serve test lint typecheck eval eval-seeds sweep clean

VENV := .venv
PY := $(VENV)/bin/python
PIP := $(VENV)/bin/pip

# Interpreter used to build the venv. Override when the default `python3` is a
# release some dependency has no wheel for yet:
#   make install PYTHON=python3.12
PYTHON ?= python3

install:
	$(PYTHON) -m venv --clear $(VENV)
	$(PIP) install -q --upgrade pip
	$(PIP) install -q -r requirements.txt
	@$(PY) -c "import sys; print(f'installed on Python {sys.version.split()[0]}')"
	@echo "installed. next: cp .env.example .env && edit, then make demo"

cims:
	$(PY) -m scripts.generate_cims

demo: cims
	$(PY) -m scripts.run_demo

seed: cims
	$(PY) -m scripts.run_demo --all --seed

serve:
	$(VENV)/bin/uvicorn app.main:app --reload --port 8000

test:
	$(VENV)/bin/pytest -q

lint:
	$(VENV)/bin/ruff check app scripts evals tests
	$(VENV)/bin/ruff format --check app scripts evals tests

typecheck:
	$(VENV)/bin/mypy app

eval:
	$(PY) -m evals.run_evals

# Score the memos already generated by `make seed` — no API calls, no cost.
eval-seeds:
	$(PY) -m evals.run_evals --from-seeds

sweep:
	$(PY) -m evals.sweep_effort

clean:
	rm -rf .pytest_cache .mypy_cache .ruff_cache **/__pycache__ *.db
